//Thought process behind this project: its a bit lengthy, so we have to break it into steps
/* First lets have all the elements we need to select, and everything we need */
/* What this project is doing?
We are giving 10 chances to user to guess the number(1 to 100),
and check whether it matches with the random number generated by Math.random()

Here, with each guess, we will display the user guess and whether their guess is high/low or they won. Then we will decrease the remaining guesses.
Here, we also need to show the previous guesses made by the user. Sir had used an array also to store the previous guesses, but why? to make the project scalable and answer questions like whether the user has already guessed the current number

endGame() after 10 guesses or on winning
Then resetting everything the guess field, prevGuess[], the display of previous guesses on screen(Html) and guess remaining
And show a Play again button*/

let randomNum = parseInt((Math.random() * 100) + 1);
// console.log(randomNum);

//HTML node selectors
const userInput = document.querySelector('#guessField');
const submit = document.querySelector('#subt'); 
const startOver = document.querySelector('.resultParas'); 
const guessSlot = document.querySelector('.guesses'); 
const remaining = document.querySelector('.lastResult'); 
const lowOrHi = document.querySelector('.lowOrHi'); 

const p = document.createElement('p');

let prevGuess = [];
let numGuess = 1;

let playGame = true;

if(playGame) {
  submit.addEventListener('click', (e) => {
    e.preventDefault();
    const guess = parseInt(userInput.value);
    validateGuess(guess);
  });
}


//Functions
function validateGuess (guess){
  if(isNaN(guess)) {
    alert(`Please input valid number`);
  }else if(guess < 1 || guess > 100){
    alert(`Please enter a number between 1 to 100`);
  }else {
    //Excellent code
    prevGuess.push(guess);//For js proof of guesses
    if(numGuess === 11){
      displayGuess(guess);
      displayMessage(`Game over. Random number was ${randomNum}.`);
      endGame();
    }else {
      checkGuess(guess);
      displayGuess(guess);
    }
  }  
}
function checkGuess (guess){
  if(guess < randomNum) {
    displayMessage(`Number is TOOO low`);
  }else if(guess > randomNum) {
    displayMessage(`Number is TOOO high`);
  }//As the guess is already validated(i.e. b/w 1 to 100), and now checked for > or <. So only one option left guess == randomNum
  else {
    displayMessage(`You guessed it right!`);
    endGame();
  }
}
function displayGuess (guess){
  //Resetting the input field after guess
  userInput.value = '';
  //Showing guesses made, and previous guesses
  guessSlot.innerHTML += `${guess}, `;
  //Num of guesses made
  numGuess++;
  // calculating & displaying remaining count of guesses
  remaining.innerHTML =`${11 - numGuess}`;
}
//Showing the display message
function displayMessage (message){
  lowOrHi.innerHTML = `<h2>${message}</h2>`;
}
function endGame (){
  userInput.value = '';
  userInput.setAttribute('disabled', '');
  p.classList.add('button');
  p.innerHTML = `<h2 id="newGame">Play Again!</h2>`;
  startOver.appendChild(p);
  playGame = false;
  newGame();
}
function newGame (){//Resetting everything 
  //Adding event listener to new game button
  const newGameButton = document.querySelector('#newGame');
  newGameButton.addEventListener('click', (e) => {
    randomNum = parseInt((Math.random() * 100) + 1);
    prevGuess = [];
    numGuess = 1
    guessSlot.innerHTML = '';
    remaining.innerHTML = `${11 - numGuess}`;
    userInput.removeAttribute('disabled');
    startOver.removeChild(p);
    playGame = true;
  });  
}
